name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
    unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [20, 24]
        operating_system: [ubuntu-latest]
        exclude:
          - nodejs_version: 18
            operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.nodejs_version }}


      - name: Cache NPM dependencies
        uses: actions/cache@v5
        with:
          path: node_modules   #This is the folder where all your installed packages go after npm install. So we are saying Save this folder (node_modules) for reuse 
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }} #This decides when to reuse cache and when not to
          #runner.os → different cache for Linux / macOS  || package-lock.json → list of dependencies
          #If dependencies don’t change → cache is reused || If dependencies don’t change → cache is reused
      
      - name: Install Dependencies
        run: npm install

      - name: Unit Testing
        id: nodejs-unit-testing    #this name can be anything to store the outcome value of this npm test.
        run: npm test

      - name: Archive Test Result
        if: always()       # if either above npm test fail or success this archive step will always run. 
        uses: actions/upload-artifact@v5
        with:
          # Make artifact name unique per job run
          name: Mocha-Test-Result-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}-${{ github.run_id }}
          path: test-results.xml

  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup NodeJS Version - 18
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Cache NPM dependencies
        uses: actions/cache@v5
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }} 
    
      - name: Install Dependencies
        run: npm install

      - name: Check Code Coverage
        continue-on-error: true      #it will skip the error and let the remaining steps contineue without stoping the workflow.
        run: npm run coverage

      - name: Archive Test Result
        uses: actions/upload-artifact@v5
        with:
          name: Code-Coverage-Result
          path: coverage
          retention-days: 5


  docker:
    name: Containerization
    needs: [unit-testing, code-coverage] #So this docker login job only run when these 2 will complete.
    permission:
       packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: GHCR Login   #(Git hub container registery)
      uses: docker/login-action@v2.2.0
      with:
          registery: ghcr.io
          username: $ {{ github.Repository.owner }}
          password: ${{ secrets.GITHUB_TOKEN }} #you have to add permission also like above in job leve step (write permission that we add) otherwise it will only have reaad permission 
          

      - name: Docker Build for Testing
        uses: docker/build-push-action@v7
        with:
          context: .  #path where you have your docker file
          push: false #it false that means after the docker image build it will not push the code into the image
          tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

      
      - name: Docker Image Testing
        run: |
          docker images
          docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MONGO_URI=$MONGO_URI \
              -e MONGO_USERNAME=$MONGO_USERNAME \
              -e MONGO_PASSWORD=$MONGO_PASSWORD \
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}  #at this step image/container started.
 
           export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
           echo $IP  #to test the containers you need ip adderess, so export ip comes in place.

           echo Testing Image URL using wget
           wget -q -O - 127.0.0.1:3000/live | grep live 
           #this to check of container running or not, it give status live, so build and testing of docker will be done till this step.
     
      - name: Docker Push and to container registery
        uses: docker/build-push-action@v7
        with:
          context: .  #path where you have your docker file
          push: true #true means after the docker image build it will push the code into the image
          tags: |
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
      









